from datetime import datetime as dt
import bcrypt
from app.models import db

class User(db.Model):
    """
    Core User model representing a platform account.
    
    Hashed passwords are stored using bcrypt to ensure security.
    Notification preferences are stored directly to simplify querying for the Alert service.
    """
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    
    # User-specific notification preferences
    notification_email = db.Column(db.String(120))
    slack_webhook_url = db.Column(db.String(512))
    
    created_at = db.Column(db.DateTime, default=dt.utcnow)
    monitors = db.relationship('Monitor', backref='owner', lazy=True)

    def set_password(self, password: str):
        """
        Hashes and sets the user's password.
        
        Uses a salt generated by bcrypt to prevent rainbow table attacks.
        """
        salt = bcrypt.gensalt()
        self.password_hash = bcrypt.hashpw(password.encode('utf-8'), salt).decode('utf-8')

    def check_password(self, password: str) -> bool:
        """
        Verifies a provided password against the stored hash.
        
        Using bcrypt's checkpw avoids timing attacks by using constant-time comparison.
        """
        return bcrypt.checkpw(password.encode('utf-8'), self.password_hash.encode('utf-8'))
